### ISSUE TITLE
isothermal disk model failing

### ISSUE THREAD

**Issue by kslong** [Higginbottom/pluto#2]
The isothermal disk model is failing both with gcc and mpicc at the start of the run with a NAN on the blondin43 branch, see:

[foo.txt](https://github.com/Higginbottom/pluto/files/2581496/foo.txt)

**Comment by saultyevil** [comment]
Same issue for me. There are some warnings related to pointers when compiling init.c, e.g.

```
init.c:162:6: warning: incompatible pointer types assigning to 'double *' from 'double *[3]' [-Wincompatible-pointer-types]
  x1 = grid[IDIR].x;
```

Could this be a potential cause of the problem?

**Comment by jhmatthews** [comment]
Think those pointers changed between 4.2 and 4.3 - I guess that’s probably it.

**Comment by Higginbottom** [comment]
Exactly right - I have updated the isothermal init.c file - not sure why the wrong one is in the repo…

Will fix...

**Comment by Higginbottom** [comment]
Right - I forgot to push the change!
fixed now…

**Comment by kslong** [comment]
Yep. Works for me now, so I am closing the issue.  Thanks,  everyone.
